import numpy as np

def poly_mul(p1, p2, mod=7):
    # Standard polynomial multiplication in Z7
    res = np.zeros(len(p1) + len(p2) - 1, dtype=int)
    for i, a in enumerate(p1):
        for j, b in enumerate(p2):
            res[i+j] = (res[i+j] + a * b) % mod
    return res

def generate_rune129_codebook(num_ids=10):
    # Polynomials from the screenshot (lowest degree first)
    p1 = [1, 4, 1, 6, 1, 4, 1]
    p2 = [1, 0, 2, 2, 2, 0, 1]
    p3 = [1, 1, 3, 5, 3, 1, 1]
    p4 = [1, 5, 5, 0, 5, 5, 1]
    p5 = [1, 6, 0, 2, 0, 6, 1]
    p6 = [1, 6, 4, 3, 4, 6, 1]

    # Multiply all 6 polynomials to get g(x)
    gx = p1
    for p in [p2, p3, p4, p5, p6]:
        gx = poly_mul(gx, p)
    
    # g(x) has degree 36. Codeword length is 43. 
    # Dimension is 43 - 36 = 7.
    # Codewords are generated by c(x) = i(x) * g(x) 
    # where i(x) is an info polynomial of degree < 7.
    
    codes = []
    # Generate first num_ids info polynomials
    for i in range(num_ids):
        # Convert i to base 7 info vector
        info = []
        temp = i
        for _ in range(7):
            info.append(temp % 7)
            temp //= 7
            
        # Multiply info polynomial by g(x)
        codeword = np.zeros(43, dtype=int)
        for deg, coeff in enumerate(info):
            if coeff == 0: continue
            for g_deg, g_coeff in enumerate(gx):
                idx = (deg + g_deg) % 43 # Cyclic shift? 
                # Actually, standard cyclic code is just shift. 
                # c = i * g
                codeword[deg + g_deg] = (codeword[deg + g_deg] + coeff * g_coeff) % 7
        
        codes.append((i, codeword))
    return codes

if __name__ == "__main__":
    new_codes = generate_rune129_codebook(8) # IDs 0-7
    for id_val, code in new_codes:
        code_str = " ".join(map(str, code))
        # Format: ID 43 SYMBOLS...
        print(f"{id_val} 43 {code_str}")
