name: Build and Push Docker Image

on:
  push:
    branches: [ "main", "CCtag", "runetag" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase repo owner
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
          echo "BRANCH_LC=${BRANCH,,}" >>${GITHUB_ENV}
        env:
          OWNER: "${{ github.repository_owner }}"
          BRANCH: "${{ github.ref_name }}"

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./tracker
          push: true
          tags: ghcr.io/${{ env.OWNER_LC }}/owlbear-tracker:${{ env.BRANCH_LC }}
